# -*- coding: utf-8 -*-
# Created by: PyQt5 UI code generator 5.9.2

from PyQt5 import QtCore, QtGui, QtWidgets
from serial.tools import list_ports

import icons_rc

class Ui_comSettingsDialog(object):
    def setupUi(self, comSettingsDialog):
        comSettingsDialog.setObjectName("comSettingsDialog")
        comSettingsDialog.resize(268, 160)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/T4G.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        comSettingsDialog.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(comSettingsDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(comSettingsDialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.portCbBox = QtWidgets.QComboBox(self.frame)
        self.portCbBox.setMinimumSize(QtCore.QSize(0, 25))
        self.portCbBox.setObjectName("portCbBox")
        self.portCbBox.addItem("")
        self.portCbBox.addItem("")
        self.portCbBox.addItem("")
        self.portCbBox.addItem("")
        self.portCbBox.addItem("")
        self.horizontalLayout_2.addWidget(self.portCbBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.brCbBox = QtWidgets.QComboBox(self.frame)
        self.brCbBox.setMinimumSize(QtCore.QSize(0, 25))
        self.brCbBox.setObjectName("brCbBox")
        self.brCbBox.addItem("")
        self.brCbBox.addItem("")
        self.horizontalLayout.addWidget(self.brCbBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.connectButton = QtWidgets.QPushButton(self.frame)
        self.connectButton.setMinimumSize(QtCore.QSize(0, 25))
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_3.addWidget(self.connectButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.portCbBox2 = QtWidgets.QComboBox(self.frame_2)
        self.portCbBox2.setMinimumSize(QtCore.QSize(0, 25))
        self.portCbBox2.setObjectName("portCbBox2")
        self.portCbBox2.addItem("")
        self.portCbBox2.addItem("")
        self.portCbBox2.addItem("")
        self.portCbBox2.addItem("")
        self.portCbBox2.addItem("")
        self.horizontalLayout_9.addWidget(self.portCbBox2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.brCbBox2 = QtWidgets.QComboBox(self.frame_2)
        self.brCbBox2.setMinimumSize(QtCore.QSize(0, 25))
        self.brCbBox2.setObjectName("brCbBox2")
        self.brCbBox2.addItem("")
        self.brCbBox2.addItem("")
        self.horizontalLayout_10.addWidget(self.brCbBox2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.connectButton2 = QtWidgets.QPushButton(self.frame_2)
        self.connectButton2.setMinimumSize(QtCore.QSize(0, 25))
        self.connectButton2.setObjectName("connectButton2")
        self.horizontalLayout_8.addWidget(self.connectButton2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.closeButton = QtWidgets.QPushButton(comSettingsDialog)
        self.closeButton.setMinimumSize(QtCore.QSize(0, 25))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_4.addWidget(self.closeButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)

        self.retranslateUi(comSettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(comSettingsDialog)

    def retranslateUi(self, comSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        comSettingsDialog.setWindowTitle(_translate("comSettingsDialog", "Serial Port Communication Settings"))
        self.label.setText(_translate("comSettingsDialog", "Port 1:"))
        #Modified/added #################################################################
        ports = list(list_ports.comports())
        count = 0
        for it in ports:
            self.portCbBox.setItemText(count, _translate("comSettingsDialog", str(it)))
            self.portCbBox2.setItemText(count, _translate("comSettingsDialog", str(it)))
            count += 1
        #################################################################################
        self.label_2.setText(_translate("comSettingsDialog", "Baud rate 1:"))
        self.brCbBox.setItemText(0, _translate("comSettingsDialog", "9600"))
        self.brCbBox.setItemText(1, _translate("comSettingsDialog", "115200"))
        self.connectButton.setText(_translate("comSettingsDialog", "Connect"))
        self.label_5.setText(_translate("comSettingsDialog", "Port 2:"))
        self.label_6.setText(_translate("comSettingsDialog", "Baud rate 2:"))
        self.brCbBox2.setItemText(0, _translate("comSettingsDialog", "9600"))
        self.brCbBox2.setItemText(1, _translate("comSettingsDialog", "115200"))
        self.connectButton2.setText(_translate("comSettingsDialog", "Connect"))
        self.closeButton.setText(_translate("comSettingsDialog", "Close"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    comSettingsDialog = QtWidgets.QDialog()
    ui = Ui_comSettingsDialog()
    ui.setupUi(comSettingsDialog)
    comSettingsDialog.show()
    sys.exit(app.exec_())

