# -*- coding: utf-8 -*-
# Created by: PyQt5 UI code generator 5.9.2


from PyQt5 import QtCore, QtGui, QtWidgets

from graphswidget import GraphsWidget
import icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 399)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/T4G.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.configurationButton = QtWidgets.QPushButton(self.frame)
        self.configurationButton.setMinimumSize(QtCore.QSize(0, 25))
        self.configurationButton.setObjectName("configurationButton")
        self.horizontalLayout_3.addWidget(self.configurationButton)
        self.findDeviceButton = QtWidgets.QPushButton(self.frame)
        self.findDeviceButton.setEnabled(False)
        self.findDeviceButton.setMinimumSize(QtCore.QSize(0, 25))
        self.findDeviceButton.setObjectName("findDeviceButton")
        self.horizontalLayout_3.addWidget(self.findDeviceButton)
        self.startButton = QtWidgets.QPushButton(self.frame)
        self.startButton.setEnabled(False)
        self.startButton.setMinimumSize(QtCore.QSize(0, 25))
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_3.addWidget(self.startButton)
        self.nextButton = QtWidgets.QPushButton(self.frame)
        self.nextButton.setEnabled(False)
        self.nextButton.setMinimumSize(QtCore.QSize(0, 25))
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_3.addWidget(self.nextButton)
        self.stopButton = QtWidgets.QPushButton(self.frame)
        self.stopButton.setEnabled(False)
        self.stopButton.setMinimumSize(QtCore.QSize(0, 25))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_3.addWidget(self.stopButton)
        self.removeDeviceButton = QtWidgets.QPushButton(self.frame)
        self.removeDeviceButton.setEnabled(False)
        self.removeDeviceButton.setMinimumSize(QtCore.QSize(0, 25))
        self.removeDeviceButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.removeDeviceButton.setObjectName("removeDeviceButton")
        self.horizontalLayout_3.addWidget(self.removeDeviceButton)
        self.saveSessionButton = QtWidgets.QPushButton(self.frame)
        self.saveSessionButton.setEnabled(False)
        self.saveSessionButton.setMinimumSize(QtCore.QSize(0, 25))
        self.saveSessionButton.setObjectName("saveSessionButton")
        self.horizontalLayout_3.addWidget(self.saveSessionButton)
        self.exitButton = QtWidgets.QPushButton(self.frame)
        self.exitButton.setMinimumSize(QtCore.QSize(0, 25))
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout_3.addWidget(self.exitButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.GraphArea = GraphsWidget(self.frame_3)
        self.GraphArea.setEnabled(True)
        self.GraphArea.setObjectName("GraphArea")
        self.gridLayout_3.addWidget(self.GraphArea, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 110))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.messagesBox = QtWidgets.QPlainTextEdit(self.frame_2)
        self.messagesBox.setMinimumSize(QtCore.QSize(0, 90))
        self.messagesBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.messagesBox.setObjectName("messagesBox")
        self.gridLayout_2.addWidget(self.messagesBox, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 621, 18))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "T4G - Mould Monitoring System"))
        self.configurationButton.setText(_translate("MainWindow", "Configuration"))
        self.findDeviceButton.setText(_translate("MainWindow", "Find Device"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.removeDeviceButton.setText(_translate("MainWindow", "Remove Devices"))
        self.saveSessionButton.setText(_translate("MainWindow", "Save Session"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
